require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['namespace', 'describe', 'context']
  Exclude:
    - 'config/**/*'

Metrics/LineLength:
  Max: 120

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/AndOr:
  EnforcedStyle: conditionals
