require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['namespace', 'describe', 'context']

Metrics/LineLength:
  Max: 120

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Rspec/NestedGroup:
  MaxNesting: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
